### ISSUE TITLE
Roadmap for stable

### ISSUE THREAD

**Issue by ilaicraftYT** [ilaicraftYT/arkmc#2]
Tasks on the following order:
- [ ] Solve #1 and any upcoming issues related to packet management.
- [ ] Create PR & Issues templates.
- [ ] Clear code.
- [ ] Setup GH actions for automated builds and lints and maybe add a standalone executable.
- [ ] Create base for creating commands on the chat.
- [ ] Make actual utilities (for not saying cheats).
- [ ] Utility: Speed.
- [ ] Utility: Velocity (AntiKB).
- [ ] Clear code (again, because i know after this will be a mess).
- [ ] Update README.

Here we go!
